kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "finance-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/trafficparrot/trafficparrot-examples-openshift"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      type: JenkinsPipeline
      jenkinsfilePath: openshift/finance/jenkinsfile.groovy
